[tools]
"go:github.com/bazelbuild/buildtools/buildifier" = "latest"
java = "21"
node = "latest"
"npm:@bazel/buildozer" = "latest"
"npm:@bazel/ibazel" = "latest"
"npm:npm-groovy-lint" = "latest"
pnpm = "latest"


[tasks.deploy]
description = "Deploy to CloudFlare pages"
run = "bazel build //ts/web:build && wrangler pages deploy bazel-bin/ts/web/dist --branch prod"
