load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")

ts_project(
    name = "a",
    srcs = ["a.ts"],
    declaration = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
)
